services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: medicine_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./inventory.db:/inventory.db
    environment:
      - DATABASE_URL=sqlite:////inventory.db
    command: flask run --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./updatedFrontend
      dockerfile: ../Dockerfile.frontend
    container_name: medicine_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
